/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseInputNumber: typeof import('./../../components/input/BaseInputNumber.vue')['default']
    BaseLoader: typeof import('./../../components/BaseLoader.vue')['default']
    BaseSwitch: typeof import('./../../components/input/BaseSwitch.vue')['default']
    BaseTable: typeof import('./../../components/table/BaseTable.vue')['default']
    InputPreview: typeof import('./../../components/input/InputPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePreview: typeof import('./../../components/table/TablePreview.vue')['default']
  }
}
